[versions]
agp = "8.7.3"
kotlin = "2.0.21"
cacheFix = "3.0.1"

[libraries]
android-gradlePlugin-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
maven-publish = { id = "maven-publish" }
